language: java

script: mvn clean install --quiet -B

install: /bin/true

jdk:
  - openjdk7
  # No longer supported - see https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
  # - oraclejdk7

branches:
  only:
    - master

notifications:
  email:
    - mathieu.carbou@gmail.com
